# Generated by Django 4.1.5 on 2023-03-21 16:26

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Gyms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='title',
        ),
        migrations.AddField(
            model_name='data',
            name='Address',
            field=models.CharField(default=datetime.datetime(2023, 3, 21, 16, 25, 35, 500979, tzinfo=datetime.timezone.utc), max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='Email',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='Name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='Phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
    ]
