# Generated by Django 4.1.5 on 2023-03-21 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Gyms', '0002_remove_data_title_data_address_data_email_data_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='DOB',
            field=models.DateField(default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
    ]
