# Generated by Django 4.1.5 on 2023-03-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gyms', '0004_rename_gender_data_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=128),
        ),
    ]
