# Generated by Django 4.1.5 on 2023-03-31 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gyms', '0006_contact_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact_details',
            new_name='contact_detail',
        ),
    ]
